vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        heros_images:
            uri_prefix: /images/heros
            upload_destination: '%kernel.project_dir%/public/images/heros'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
